# AdminChat


permission: "skyrise.adminchat"

messages:
  format: "<dark_gray>[<dark_red>ADMIN</dark_red>]</dark_gray> <red>{player} »</red> <white>{message}"

  toggle-on: "<green>» AdminChat włączony."
  toggle-off: "<red>» AdminChat wyłączony."
