# ArmorWorld


blocked-worlds:
  - world_nether

blocked-items:
  - NETHERITE_HELMET
  - NETHERITE_CHESTPLATE
  - NETHERITE_LEGGINGS
  - NETHERITE_BOOTS

deny-message: "<red>» Zbroja jest zakazana w mieście."

bypass-permission: "skyrise.armorworld.bypass"

safety-check-interval-ticks: 10
