# Butelkomat


butelkomat-furniture-ids:
  - butelkomat

settings:
  return-all-in-hand: true
  interact-cooldown-ms: 500
  sound-volume: 0.7
  sound-pitch: 1.0

sounds:
  success: "ENTITY_EXPERIENCE_ORB_PICKUP"
  error: "ENTITY_VILLAGER_NO"

messages:
  prefix: "<bold><#459df5>Butelkomat</#459df5></bold> <gray>»</gray> "

  no-permission: "{prefix}<red>Brak uprawnień do korzystania z butelkomatu.</red>"
  not-accepted: "{prefix}<red>Ten przedmiot nie jest przyjmowany przez butelkomat!</red>"
  only-player: "{prefix}<red>Tylko gracz może tego użyć.</red>"
  invalid-price: "{prefix}<red>Podana cena jest nieprawidłowa!</red>"
  empty-hand: "{prefix}<red>Musisz trzymać przedmiot w ręce!</red>"
  invalid-index: "{prefix}<red>Podany index jest nieprawidłowy!</red>"
  not-found: "{prefix}<red>Nie znaleziono przedmiotu o takim indeksie.</red>"
  not-nexo: "{prefix}<red>Przedmiot w Twojej ręce nie pochodzi z pluginu Nexo!</red>"
  nexo-error: "{prefix}<red>Błąd API Nexo. Upewnij się, że plugin jest aktualny.</red>"
  cmd-disabled: "{prefix}<red>Ta komenda jest obecnie wyłączona.</red>"
  cmd-usage: "{prefix}<#459df5>Użycie: {0}</#459df5>"

  item-added: "{prefix}<white>Dodano przedmiot do butelkomatu! Cena: <yellow>{0}$</yellow></white>"
  item-removed: "{prefix}<white>Pomyślnie usunięto przedmiot <yellow>#{0}</yellow> z bazy.</white>"
  list-header: "{prefix}<white>Lista akceptowanych przedmiotów:</white>"
  list-empty: "  <gray>Brak akceptowanych przedmiotów.</gray>"
  list-format: "  <yellow>#{0}</yellow> <gray>-</gray> <white>{1}</white> <gray>-</gray> Cena: <yellow>{2}$</yellow>"
  model-set: "{prefix}<white>Pomyślnie powiązano! Każdy postawiony model <yellow>{0}</yellow> będzie działał jako maszyna.</white>"
  reloaded: "{prefix}<white>Pomyślnie przeładowano pliki konfiguracyjne!</white>"
  return-success: "{prefix}<white>Oddano <yellow>{0}</yellow> szt. Otrzymano: <yellow>{1}$</yellow></white>"
  machine-placed: "{prefix}<white>Pomyślnie postawiono nową maszynę Butelkomatu!</white>"
  admin-click-info: "{prefix}<white>Kliknięto mebel Nexo o ID: <yellow>{0}</yellow></white>"

items: []
