# Chat


local-radius: 40

global-cooldown: 30

global-format: "<white>[<aqua>G</aqua>]</white> <gray>{player}</gray> <dark_gray>»</dark_gray> <white>{message}</white>"

cooldown-message: "<red>» Musisz odczekać jeszcze {time} sekund przed ponownym użyciem czatu globalnego."
