# Knockout


bleedout-time: 30

revive-time: 5

messages:
  knocked-self: "<red>» Zostałeś/aś powalony/a! Masz {time}s na ratunek. Kliknij 3x Shift aby się wykrwawić."
  knocked-broadcast: "<red>» [DYSPOZYTORNIA]</red> <gray>Obywatel <white>{player}</white> został powalony! Lokalizacja: <gold>{world} ({x}, {y}, {z})</gold>"
  reviving-actionbar: "<gold>Podnoszenie: </gold>{bar}"
  revived-self: "<green>» Zostałeś/aś podniesiony/a przez <white>{player}</white>!"
  revived-other: "<green>» Podniosłeś/aś gracza <white>{player}</white>!"
  bleedout-broadcast: "<red>» Gracz <white>{player}</white> wykrwawił się na śmierć."
